### ISSUE TITLE
Lines with the translation are not displayed in the mod

### ISSUE THREAD

**Issue by Well-sp** [6d306e73746572/bagoftricks-localisation#1]
Hi. I translate the mod. Please check. Only this mod and CraftMagicItems is installed. 1255 (arrayItem_Weather_Normal) - 1377 (charStat_Initiative), 1131 (arrayItem_Alignments_NoChange) - 1157 (arrayItem_Alignments_Chaotic). And some more. But I am interested in precisely these.

http://rgho.st/private/6WYqHTrdg/5e6be388729056cec13f0ddb8882712b

**Comment by 6d306e73746572** [comment]
Hi!
Thank you the report - I'll release a fix in the next few days.

**Comment by 6d306e73746572** [comment]
Version 1.12.4 should fix your issues.
If they still persist please comment in this thread.

**Comment by Well-sp** [comment]
Hi. Few unpleasant moments.

1.  https://d.radikal.ru/d08/1902/82/da69e4067a6b.png
https://a.radikal.ru/a07/1902/d8/3cdac31edde7.png

2.   https://c.radikal.ru/c37/1902/a1/f8bfec01a8a3.png
https://a.radikal.ru/a15/1902/8b/a8e5aa1ae31c.png

3.   https://b.radikal.ru/b24/1902/ef/2bb37766941a.png
https://d.radikal.ru/d27/1902/7a/744541a56e34.png

4.   https://d.radikal.ru/d09/1902/a8/61e406fa997a.png
https://c.radikal.ru/c42/1902/2b/48d94129b703.png

5.   https://c.radikal.ru/c08/1902/08/06df6e359ce2.png

No more complaints at the moment. Thank you so much for your work on this mod.
translation to version 1.12.4 -
https://drive.google.com/open?id=1j7T_Hr7mp2cn3E1u40kQmwG3EYlE4AOK

p.s. There were many problems when comparing the text in the program. I suspect that because of the hidden Unicode control characters ... Are they in the text? I'm right? I was afraid that I would break something in the encoding ..

**Comment by 6d306e73746572** [comment]
Thank you very much for taking the time to translate the mod!
1.-4. should be fixed in the upcoming version and it will also include your translation.
5. I'll have to fix at a different time, but thank you very much for pointing this out.

The question about the Unicode control characters is honestly a bit beyond me.
I don't know if this helps: the .xml just get deserialized into strings so as long as it is a valid .xml file nothing should break.

**Comment by Well-sp** [comment]
A slight translation correction. On version 1.2.5d saves are not launched. 60+ hours of play. I was upset. Highly)). I doubt that I will play soon .. Sorry
1.2.5 - https://drive.google.com/open?id=1D4P52vOInq4K-omQRq7C1Cyb2H_X9qpo

**Comment by 6d306e73746572** [comment]
Thank you very much for the update.
No need to apologise, it's quite understandable that you aren't keen on playing the game anymore.
I'd probably feel the same.
