### ISSUE TITLE
Minor problems with user interface

### ISSUE THREAD

**Issue by Well-sp** [6d306e73746572/bagoftricks-localisation#2]
The phrase does not fit in the allotted frame. I can not reduce the number of words, as the meaning is lost. Is it possible to slightly expand the frame?
https://a.radikal.ru/a18/1902/5c/e9f37cbf2214.png
https://c.radikal.ru/c19/1902/46/21d4f646dc02.png

The problem is similar to the previous one.
https://d.radikal.ru/d42/1902/ac/3ea9919b1d47.png
https://a.radikal.ru/a00/1902/96/ff7bfd2aefdd.png

Last point. I do not understand how the "Don't Leave An Inactive Campsite" function works. Is it possible to tell a little more?

**Comment by 6d306e73746572** [comment]
I'll have a look at the issues.
After resting usually a small campfire with a ashes appears on the spot of your rest. If 'Don't Leave An Inactive Campsite' is enabled that won't happen.
