### ISSUE TITLE
Absolutely not clear the meaning of the tab

### ISSUE THREAD

**Issue by Well-sp** [6d306e73746572/bagoftricks-localisation#3]
https://a.radikal.ru/a03/1902/f7/01cc537aae94.png
https://c.radikal.ru/c28/1902/07/ac135d015b21.png

I really do not understand its function. In the English version in this tab is empty. When the language switches to Russian, spells are displayed in it. Please explain what this tab does and what should be displayed there.

**Comment by 6d306e73746572** [comment]
The menu shows all abilities of the selected character (including spells).
It's main use is to remove or favourite abilities. 

Edit1: Looks like there is an issues with all the Hide/Display buttons when switching localisation/the localisation changes these strings.
Edit2: Same is true for Enable/Disable.
